insighty-studio/website

README.md, config/env.js, config/jest/cssTransform.js, config/jest/fileTransform.js, config/paths.js, config/polyfills.js, config/webpack.config.dev.js, config/webpack.config.prod.js, config/webpackDevServer.config.js, package.json, public/index.html, yarn.lock
=> Configure stylus

package-lock.json, src/imports/components/Button/index.js, src/imports/components/Button/index.styl, src/imports/components/Input/index.styl, src/imports/components/SectionHeading/index.styl, src/imports/components/TextArea/index.js, src/imports/styles/config.styl, src/imports/styles/main.styl, src/pages/Landing/sections/ContactUs/components/Footer/index.styl, src/pages/Landing/sections/ContactUs/contact-us-section.styl, src/pages/Landing/sections/ContactUs/index.js, src/pages/Landing/sections/Main/components/Description/description.styl, src/pages/Landing/sections/Main/components/Logo/logo.styl, src/pages/Landing/sections/Main/components/NavigationBar/navigation-bar.styl, src/pages/Landing/sections/Main/main-section.styl, src/pages/Landing/sections/Services/components/Service/service.styl, src/pages/Landing/sections/Services/services-section.styl, src/pages/Landing/sections/TheProcess/components/Process/process.styl, src/pages/Landing/sections/Work/components/WorkItem/work-item.styl
=> NEW: Added button

src/imports/components/SectionHeading/index.js, src/imports/components/SectionHeading/index.styl, src/pages/Landing/sections/Main/components/Logo/index.js, src/pages/Landing/sections/Main/components/Logo/logo.styl
=> NEW: Create animation for section heading

src/imports/icons/index.js, src/pages/Landing/index.js, src/pages/Landing/landing.styl
=> NEW: Create scroll to top button

src/pages/Landing/index.js, src/pages/Landing/landing.styl
=> NEW: Added appearance/disappearance of scroll button

src/app.js, src/pages/Landing/sections/Main/components/Description/description.styl, src/pages/Landing/sections/Main/components/Description/index.js, src/pages/Landing/sections/Main/components/Logo/index.js, src/pages/Landing/sections/Main/components/NavigationBar/index.js, src/pages/Landing/sections/Main/components/NavigationBar/navigation-bar.styl, src/pages/Landing/sections/Main/index.js, src/pages/Landing/sections/Services/index.js, src/pages/Landing/sections/Services/services-section.styl, src/pages/Landing/sections/TheProcess/components/Process/index.js, src/pages/Landing/sections/TheProcess/index.js, src/pages/Landing/sections/Work/index.js, src/pages/Landing/sections/Work/work-section.styl, src/pages/Loader/index.js, src/pages/Loader/loader.styl
=> NEW: Create loading screen

config/webpack.config.dev.js, config/webpack.config.prod.js, package-lock.json, package.json, src/imports/components/ScrollToTopBtn/index.js, src/pages/Landing/index.js
=> CHANGE: Refactor Landing screen, Fix webpack config

package-lock.json, package.json, src/imports/components/TextArea/index.js, src/pages/Landing/sections/ContactUs/index.js, yarn.lock
=> NEW: Make contact us form functionable for receiving requests

src/pages/Landing/sections/ContactUs/index.js
=> CHANGE: Correct some code area

src/imports/icons/index.js, src/pages/SuperHero/sections/About/index.styl, src/pages/SuperHero/sections/Fonts/index.js, src/pages/SuperHero/sections/Fonts/index.styl
=> NEW: Create Fonts & About sections

src/pages/Landing/index.js, src/pages/Landing/index.styl, src/pages/Landing2.0/index.js, src/pages/Landing2.0/index.styl, src/pages/Landing2.0/sections/Main/index.js, src/pages/Landing2.0/sections/Main/index.styl, src/pages/Landing2.0/sections/Services/index.js, src/pages/Landing2.0/sections/Services/index.styl, src/pages/Landing2.0/sections/TheProcess/index.js, src/pages/Landing2.0/sections/Work/index.js
=> CHANGE: Refactor code

src/imports/components/SubTitle/index.styl, src/pages/Landing2.0/sections/Main/components/NavigationBar/index.styl, src/pages/Landing2.0/sections/TheProcess/components/Step/index.js
=> Fix minor styling issues

src/pages/Landing/sections/ContactUs/index.styl, src/pages/Landing/sections/Header/components/NavigationBar/index.js
=> IW-58 Fix contacts section on mobile

src/pages/Loader/index.styl
=> FIX: Fix loader

src/imports/styles/animations.styl, src/pages/Landing/index.styl, src/pages/Landing/sections/Header/index.js, src/pages/Loader/index.js, src/pages/Loader/index.styl
=> FIX: Fix loader on landing page

src/imports/components/Sections/About/index.js, src/imports/components/Sections/About/index.styl, src/imports/components/Sections/Colors/index.js, src/imports/components/Sections/Colors/index.styl, src/pages/BetterYet/sections/About/index.styl, src/pages/BetterYet/sections/Header/index.js, src/pages/BetterYet/sections/Header/index.styl, src/pages/BetterYet/sections/Illustration/index.js, src/pages/BetterYet/sections/Illustration/index.styl, src/pages/BetterYet/sections/Prototypes/index.js, src/pages/BetterYet/sections/Prototypes/index.styl
=> NEW: Add parallax to BetterYet page

src/imports/components/ContactUsForm/index.styl, src/imports/components/Loader/LoaderLine/index.styl, src/imports/components/NavigationBar/index.styl, src/imports/components/Sections/About/components/ShortDescription/index.styl, src/imports/components/Sections/Colors/components/ColorsBackground/index.styl, src/pages/BetterYet/sections/BetterYetLogo/icons/index.styl, src/pages/BetterYet/sections/BetterYetLogo/index.styl, src/pages/BetterYet/sections/Header/index.styl, src/pages/BetterYet/sections/Illustration/index.styl, src/pages/BetterYet/sections/Prototypes/index.styl, src/pages/LPMA/sections/Fonts/index.styl, src/pages/Landing/sections/Clients/index.styl, src/pages/Landing/sections/Partners/index.styl
=> IW-133, Fix background color of Contact Us Form on mobile

src/imports/components/Sections/Colors/index.js, src/imports/components/Sections/Colors/index.styl, src/pages/BetterYet/index.js, src/pages/BetterYet/sections/BetterYetLogo/index.js, src/pages/BetterYet/sections/Prototypes/index.js
=> NEW: Improve BetterYet page

.circleci/config.yml, public/index.html, src/imports/components/ContactUsForm/index.js, src/pages/LPMA/sections/Illustrations/mobile/index.styl, src/pages/Landing/sections/Clients/mobile/index.styl, src/pages/Landing/sections/Header/index.js
=> CHANGE: Change track events only for production, SEO

src/app.js, src/pages/LPMA/sections/Illustrations/mobile/index.styl, src/pages/Landing/sections/Clients/mobile/index.styl
=> NEW: Experemental height calc

src/imports/components/Footer/index.js, src/imports/components/Footer/index.styl, src/imports/components/Footer/mobile/index.styl, src/imports/components/Header/icons/index.js, src/imports/components/Header/index.js, src/imports/components/Header/index.styl, src/imports/components/Header/mobile/index.styl, src/imports/icons/backgrounds/ServicesMobileBG.js, src/pages/Intro/mobile/index.styl, src/pages/Journey/Home/index.js, src/pages/Journey/Home/mobile/index.styl, src/pages/Journey/Impact/index.js, src/pages/Journey/Impact/mobile/index.styl, src/pages/Journey/Services/index.js, src/pages/Journey/Services/index.styl, src/pages/Journey/Services/mobile/index.styl
*note to @rkrasiuk - please don't delete the branch. thanks!
=> NEW: Implement Header, Footer, Home, Services, Impact components on mobile devices

src/imports/components/Footer/index.js, src/imports/components/Footer/mobile/index.styl, src/imports/components/interactions/AnimatedButton/mobile/index.styl, src/pages/Journey/CaseStudies/mobile/index.styl, src/pages/Journey/Consultation/index.js, src/pages/Journey/Consultation/index.styl, src/pages/Journey/Consultation/mobile/index.styl, src/pages/Journey/Home/mobile/index.styl, src/pages/Journey/Services/index.js, src/pages/Journey/Services/index.styl, src/pages/Journey/Services/mobile/index.styl
=> NEW: Implement a mobile version of Consultation page + minor fixes

src/pages/Journey/CaseStudies/index.js, src/pages/Projects/BetterYet/index.js, src/pages/Projects/Hub/index.js, src/pages/Projects/LPMA/index.js
=> FIX: Remove contact form from project pages; change description of Hub4.0 case study

src/pages/Intro/index.styl, src/pages/Journey/Services/index.styl
=> FIX:  Fix 'Begin Journey' button;  Fix 'Free Consultation' button on Services page

src/pages/Journey/Home/index.js, src/pages/Journey/Home/index.styl, src/pages/Journey/Services/index.js, src/pages/Journey/Services/index.styl
=> FIX: Styling adjustments to 'Free Consultation' button on Services page; Add underline to links

src/pages/Journey/Home/index.js, src/pages/Journey/Home/index.styl, src/pages/Journey/Services/index.js, src/pages/Journey/Services/index.styl
=> FIX: Fix text transformation on Home and Services pages

src/imports/components/interactions/Button/index.styl
=> CHANGE: New button hover effects

src/pages/Journey/Consultation/index.js, src/pages/Journey/Consultation/index.styl
=> NEW: Add success message to Consultation page

src/pages/Journey/Home/mobile/index.styl
=> FIX: Hide 'More about your journey' on mobile

src/imports/components/Header/index.js, src/pages/Intro/index.js, src/pages/Journey/Home/index.js
=> CHANGE: Update copy, reorder logos
